name = "glisten"
version = "0.3.2"
description = "a shiny Gleam TCP server"
licences = ["Apache-2.0"]
repository = { type = "github", user = "rawhat", repo = "glisten" }

[dependencies]
gleam_stdlib = "~> 0.20"
gleam_otp = "~> 0.4"
gleam_http = "~> 3.0"
gleam_erlang = "~> 0.9"

[dev-dependencies]
gleeunit = "~> 0.6"
