name = "glisten"
version = "0.2.2"
description = "a shiny Gleam TCP server"
licences = ["Apache-2.0"]
repository = { type = "github", user = "rawhat", repo = "glisten" }

[dependencies]
gleam_stdlib = "~> 0.20"
gleam_otp = "~> 0.4"
gleam_http = "~> 3.0"

[dev-dependencies]
gleeunit = "~> 0.6"
