name = "glisten"
version = "0.8.0"
description = "a shiny Gleam TCP/SSL server"
licences = ["Apache-2.0"]
repository = { type = "github", user = "rawhat", repo = "glisten" }

[dependencies]
gleam_stdlib = "~> 0.28"
gleam_otp = "~> 0.6"
gleam_erlang = "~> 0.19"

[dev-dependencies]
gleeunit = "~> 0.10"
